menu:
  主页: /
  关于我: /about

beian:
  enable: false
  icp: 省ICP备xxxxx号

sidebar:
  avatar: /images/logo.png
  # notice: xxxx
  category: true
  github: https://github.com/wss-git

baidu: 054c238bc337655f2ef34a5af8098111
bing: 14FF423612C0A4708FDEB172F79C7029

# https://beaudar.lipk.org/
beaudar:
  repo: wss-git/blog
  branch: main